name: workflow name
on: push
jobs:
    job1:
        name: job1 name
        runs-on: ubuntu-latest
        steps:
            - name: step1
              uses: actions/checkout@v4
            - name: step2
              run: ls-la
            - run: pwd
    job2:
        name: second job to run
        runs-on: windows-latest
        steps:
            - name: step one of job2
              uses: actions/checkout@v4
            - name: step two of job2
              run: pwd
              
      
        
            
            
          
            
